name: Telegram Notifier

on:
  schedule:
    - cron: '0 1 * * *'   # jalan setiap hari jam 08:00 WIB (1 UTC)
  workflow_dispatch:       # bisa dijalankan manual juga

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run notifier
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python telegram_notifier.py
